#+TITLE: Пакеты прикладных программ. Весна 2017
#+AUTHOR: Артем Пьяных
#+LATEX_HEADER: \usepackage[T2A]{fontenc}
#+LATEX_HEADER: \usepackage[english, russian]{babel}
#+LANGUAGE: ru
#+OPTIONS: ':t toc:2

* Цель курса
Основной целью данного курса является знакомство с современными практиками и инструментами, включая:
- работу с системой контроля версий,
- совместную работу над задачами при помощи Github,
- работу с динамически типизированными языками программирования (R, Python)
- использование Jupyter и RStudio для быстрого прототипирования и визуализации полученных результатов,
- автоматизированное тестирование кода,
- etc.

* Необходимое ПО
Для того, чтобы начать выполнять задания достаточно установить:
- [[https://git-scm.com][git]] --- система контроля версий,
- [[https://www.continuum.io/downloads][Anaconda]] --- готовый дистрибутив со всем необходимым, чтобы начать работать с Python,
- [[https://www.rstudio.com/products/rstudio/download3/][RStudio]] и [[https://cran.rstudio.com][R]] --- все, что необходимо, чтобы начать работать с R.
Потенциально, все нужное ПО доступно для Windows, Linux и Mac OS.
Однако, пользователям Windows рекомендуется подумать о переходе на Unix-like систему.

В том случае, если для выполнения какого-то потребуется установить дополнительное ПО, об этом будет сказано отдельно.

* Выполнение и сдача заданий
  :PROPERTIES:
  :CUSTOM_ID: submission-rules
  :END:
Каждое задание должно содержать:
- Рабочий код и другие ресурсы, решающие поставленную задачу.
- Файл README.md или README.org с:
  1. кратким описанием задачи и подхода к решению,
  2. инструкцией по запуску, включая необходимое дополнительное ПО,
  3. если задание выполняется группой --- список участников группы с описанием вклада каждого участника.

Задания могут выполняться группой до 3х человек.

Все задания в том или ином виде должны быть оформлены в виду [[https://help.github.com/articles/creating-a-pull-request/][Pull Request'a]] в данный репозиторий.
Корневой директорией для сдачи N-го задания является папка ~submissions/taskN/names-of-participants~.
Бранч для Pull Request'а должен называться ~taskN-names-of-participants~.

*Пример*.
Студенты Иванов и Петров решили вместе выполнять задание 2.
Первым делом они клонируют себе текущий репозиторий.
Делают бранч ~task2-ivanov-petrov~ от последнего ~master~.
Создают директорию ~submissions/task2/ivanov-petrov~ в которой будут содержаться все файлы относящиеся к их заданию.
После того, как они закончили выполнение задания, они посылают Pull Request в ~master~ с именем *Задание 2. Иванов, Петров*.

С этого момента задание находится в процессе ревью.
Задание считается засчитанным, после успешного прохождения ревью.

Для каждого задания установлены сроки:
- сдачи, когда должен быть готов код и создан PR в текущий репозиторий;
- прохождения ревью (обычно +1 неделя к сроку сдачи), необходимо для того, чтобы студенты могли учесть замечания.
Если задание проходит ревью после указанного срока, то Вы получаете за него только *50%*.

* Вопросы и обсуждения
Для каждого репозитория Github дает возможность заводить *Issues*.
В случае, если у Вас повляются вопросы по заданиям или по курсу, заведение issue является предпочтительным способом коммуникации, в силу того, что в отличие от почты:
- issue доступен для просмотра всем студентам,
- обсуждение гораздо нагляднее,
- студенты могут помогать друг другу отвечать на вопросы.

* Задания
- [[./tasks/task1.org][Задание 1]]

* Полезные ресурсы
** Python
- [[https://www.codecademy.com/][Codecademy]] --- онлайн платформа с вводными курсами по различным языкам программирования, в том числе Python
- [[https://www.scipy.org/][SciPy]] --- библиотека методов для научных вычислений, в том числе численного интегрирования и оптимизации
- [[http://www.numpy.org/][NumPy]] --- библиотека для работы с матрицами
- [[http://pandas.pydata.org/][Pandas]] --- библиотека для работы со структурированными данными
- [[http://matplotlib.org/][Matplotlib]] --- библиотека для работы с графиками
- [[https://jupyter.org/][Jupyter]] --- инструмент для интерактивной работы с Python-кодом
** R
- [[https://www.datacamp.com/][Datacamp]] --- онлайн платформа с курсами по R, начиная с основ языка и манипуляции данными, заканчивая анализом и визуализацией
- [[https://www.rstudio.com/][RStudio]] --- IDE для работы с R-кодом
** MOOCS
- [[https://www.coursera.org/browse/computer-science?languages=en][Coursera -- Computer Science]] --- набор курсов и специализаций по программированию
- [[https://www.coursera.org/browse/data-science?languages=en][Coursera -- Data Science]] --- набор курсов и специализаций по анализу данных
