#+TITLE: Пакеты прwкладных программ. Весна 2017. Задание 1
#+OPTIONS: toc:nil

* Описание
  В этом задании вам предстоит провести анализ некоторого временного ряда и попробовать предсказать значения для последующих месяцев.
  В рамках данного задания мы:
  - научимся правильно считывать данные и их визуализировать;
  - поймем как определять свойства временных рядов и познакомимся с различными моделями для предсказания значений;
  - оценим качество полученных моделей.

  Цель *задания 1* в изучении пакета статистического анализа R, попутно познакомиться с такими библиотеками, как xts и zoo (временные ряды).

  Что вам предстоит сделать:
  1. Считать данные из [[file:task1/training.csv::#training-data][training.csv]]. Ответы на тестовой выборке [[file:task1/testing.csv::#testing-data][testing.csv]] не следует использовать ни в каких экспериментах, кроме финального. Проверить является ли ряд стационарным в широком смысле. Это можно сделать двумя способами: 
    1. Провести визуальную оценку, отрисовав ряд и скользящую статистику(среднее, стандартное отклонение). Постройте график на котором будет отображен сам ряд и различные скользящие статистики.
    2. Провести тест Дики - Фуллера.
    Сделать выводы из полученных результатов. Оценить достоверность статистики. (25 баллов)
  3. Разложить временной ряд на тренд, сезональность, остаток в соответствии с аддитивной, мультипликативной моделями. Визуализировать их, оценить стационарность получившихся рядов, сделать выводы. (15 баллов)
  4. Проверить является ли временной ряд интегрированным порядка ~k~. Если является, применить к нему модель ARIMA, подобрав необходимые параметры с помощью функции автокорреляции и функции частичной автокорреляции. Выбор параметров обосновать. Отобрать несколько моделей. Предсказать значения для тестовой выборки. Визуализировать их, посчитать ~r2 score~ для каждой из моделей. Произвести отбор наилучшей модели с помощью информационного критерия Акаике. Провести анализ получившихся результатов. (50 баллов)

  За все правильно выполненные пункты можно получить 100 баллов.

  +10 баллов - использование для визуализации библиотеки ggplot2. Надо сделать, чтобы было красиво_:).

  Вы можете использовать различные статистические модели и методы машинного обучения(ARIMA, ES, ARFIMA, LSTM, различные виды регрессий, etc).

* Сдача
  Задание *должно* выполнять группой из 2-3 человек
  Процесс стандартный, и описан в ~README.org~, секция [[file:~/../../README.org::#submission-rules][Выполнение и сдача заданий]].
  Весь анализ должен быть оформлен в виде RMarkdown документа.

* Сроки
- Сдача до 12 марта 2017г.
- Прохождение ревью до 22 марта 2016г.

