---
title: "Task 1"
author: "Komissarov, Maksimov, Oblygina"
date: '4 марта 2017 г '
output: html_document
---

```{r setup, echo=FALSE}
library(xts)
library(zoo)
library(tseries)
library(forecast)
library(MLmetrics)
```

## Reading of data


```{r read}
ts <- read.csv.zoo("training.csv",
                   index.column = 1,
                   FUN = as.Date, format = "%Y-%m-%d")
```


```{r, echo=FALSE}
plot(ts)
lines(rollmean(ts, 20), col = 2)
lines(rollmean(ts, 100), col = 3)
```

## Dickey-Fuller

You can also embed plots, for example:

```{r adf}
adf.test(ts, k = 0)
```

## Decomposition

ddldldl

```{r decompose}
ts.monthly <- zooreg(ts, frequency = 12, start = c(1959, 1))
ts.add <- decompose(as.ts(ts.monthly), type = "additive")
ts.mul <- decompose(as.ts(ts.monthly), type = "multiplicative")
plot(ts.dec)
plot(ts.mul)
```

Вывод по графикам

```{r adf on decomposition}
adf.test(na.remove(ts.mul$trend), k = 0)
adf.test(na.remove(ts.mul$seasonal), k = 0)
```

Вывод по ДФ

## Order of integration

```{r toto}
ts.diff <- diff(ts, differences = 1)
plot(ts.diff)
adf.test(ts.diff, k = 0)
```

Вывод о порядке интегрированности

## Correlation coefficients

```{r acfpacf}
acf(coredata(ts.diff))
pacf(coredata(ts.diff))
```

Предположения о (p, d, q)

```{r arima}
ts.arimaF = Arima(ts.monthly, order = c(4, 1, 6), include.drift = F)
```
blabla
```{r dorima}

```
